# https://hub.docker.com/r/bitnami/matomo
version: "3.5"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - MARIADB_USER=${MARIADB_USER:-bn_matomo}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-bitnami_matomo}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dbpassword}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-dbrootpassword}
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "./mariadb_data:/bitnami/mariadb"
  matomo:
    image: docker.io/bitnami/matomo:4
    ports:
      - "${MATOMO_SERVE_PORT:-80}:8080"
      - "443:8443"
    environment:
      - MATOMO_DATABASE_HOST=${MATOMO_DATABASE_HOST:-mariadb}
      - MATOMO_DATABASE_PORT_NUMBER=${MATOMO_DATABASE_PORT_NUMBER:-3306}
      - MATOMO_DATABASE_USER=${MATOMO_DATABASE_USER:-bn_matomo}
      - MATOMO_DATABASE_NAME=${MATOMO_DATABASE_NAME:-bitnami_matomo}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD:-dbpassword}
      - MATOMO_PASSWORD=${MATOMO_PASSWORD:-matomopassword}
      - MATOMO_ENABLE_PROXY_URI_HEADER=${MATOMO_ENABLE_PROXY_URI_HEADER:-yes}
      - MATOMO_WEBSITE_HOST=${MATOMO_WEBSITE_HOST:-https://exampleendpoint.org}
    volumes:
      - "./matomo_data:/bitnami/matomo"
    depends_on:
      - mariadb